%token <NSNumber> NUMBER
%token IDENTIFIER PGR VAR INT FLOAT ELSE PRINT INT FLOAT IF COMMA EQ DIF LT
GT LBRACE RBRACE DIVIDE TIMES LPAREN RPAREN PLUS MINUS SEMICOLON COLON CTEF CTES ID MAIN DOUBLE INPUT CHAR CONST RTN BOOLEAN INTEGERCLASS STRINGCLASS WHILE LSBRAKE RSBRAKE NEW CPTRG INCPTRG AND OR QM

%token <NSNumber> CTEI


%start program

%%
    
    program : 'program';

